---
- name: List VPC Images and Instance Profiles
  hosts: localhost
  collections:
   - ibm.cloudcollection

  tasks:
    - ibm_is_images_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
      register: images_list

    - debug:
        var: images_list.resource.images |
             items2dict(key_name='name', value_name='id')
